//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Cirrious.FluentLayout")]
[assembly: AssemblyDescription("Easy API for using AutoLayout in iOS")]
[assembly: AssemblyProduct("Cirrious.FluentLayout")]
[assembly: AssemblyVersion("2.7.0")]
[assembly: AssemblyFileVersion("2.7.0")]
[assembly: AssemblyCopyright("Copyright (c) 2013 - 2018")]

